---
apiVersion: v1
kind: Secret
metadata:
  name: aws-account-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials: W2RlbW8tY3JdIGF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVJUUkpETTVENU9BNk1EVjUgYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gdmZBZ1VIQkNEWUF3WDBoL0JtWWhIdnI0V2U2UDdFWnFmajZSV0dGZwo=
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-account-creds
      key: credentials
