---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-public-crossplane-subnet1
  labels:
    vpc: my-basic-crossplane-vpc
    publicOrPrivate: 'public'
    availabilityZone: eu-west-2a
spec:
  forProvider:
    region: eu-west-2
    availabilityZone: eu-west-2a
    vpcIdRef:
      name: my-basic-crossplane-vpc
    cidrBlock: 10.0.0.0/24
    mapPublicIPOnLaunch: true
    tags:
    - key: Name
      value: my-public-crossplane-subnet1
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-public-crossplane-subnet2
  labels:
    vpc: my-basic-crossplane-vpc
    publicOrPrivate: 'public'
    availabilityZone: eu-west-2b
spec:
  forProvider:
    region: eu-west-2
    availabilityZone: eu-west-2b
    vpcIdRef:
      name: my-basic-crossplane-vpc
    cidrBlock: 10.0.1.0/24
    mapPublicIPOnLaunch: true
    tags:
    - key: Name
      value: my-public-crossplane-subnet2