---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: my-public-crossplane-rt
spec:
  forProvider:
    region: eu-west-2
    associations:
      - subnetIdSelector:
          matchLabels:
            vpc: my-basic-crossplane-vpc
            publicOrPrivate: public
            availabilityZone: eu-west-2a
      - subnetIdSelector:
          matchLabels:
            vpc: my-basic-crossplane-vpc
            publicOrPrivate: public
            availabilityZone: eu-west-2b
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef: 
          name: my-basic-crossplane-igw
    vpcIdRef:
      name: my-basic-crossplane-vpc
    tags:
    - key: Name
      value: my-public-crossplane-rt
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: my-private-crossplane-rt-eu-west-2a
spec:
  forProvider:
    region: eu-west-2
    associations:
      - subnetIdSelector:
          matchLabels:
            vpc: my-basic-crossplane-vpc
            publicOrPrivate: private
            availabilityZone: eu-west-2a
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        natGatewayIdRef: 
          name: my-crossplane-nat1
        # Does not work!!
        # natGatewayIdSelector:
        #   matchControllerRef: true
        #   matchLabels: 
        #     availabilityZone: eu-west-2a
    vpcIdRef:
      name: my-basic-crossplane-vpc
    tags:
    - key: Name
      value: my-private-crossplane-rt-eu-west-2a
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: my-private-crossplane-rt-eu-west-2b
spec:
  forProvider:
    region: eu-west-2
    associations:
      - subnetIdSelector:
          matchLabels:
            vpc: my-basic-crossplane-vpc
            publicOrPrivate: private
            availabilityZone: eu-west-2b
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        natGatewayIdRef: 
          name: my-crossplane-nat2
        # Does not work!!
        # natGatewayIdSelector:
        #   matchControllerRef: true
        #   matchLabels: 
        #     availabilityZone: eu-west-2a
    vpcIdRef:
      name: my-basic-crossplane-vpc
    tags:
    - key: Name
      value: my-private-crossplane-rt-eu-west-2a      